[[redirects]]
    from = "/"
    to = "/html/home.html"
    status = 200

[[redirects]]
    from = "/home.html"
    to = "/html/home.html"
    status = 200

[[redirects]]
    from = "/about.html"
    to = "/html/about.html"
    status = 200

[[redirects]]
    from = "/applications.html"
    to = "/html/applications.html"
    status = 200

[[redirects]]
    from = "/in-progress.html"
    to = "/html/in-progress.html"
    status = 200

[[redirects]]
    from = "/contact.html"
    to = "/html/contact.html"
    status = 200

[[redirects]]
    from = "/skills.html"
    to = "/html/skills.html"
    status = 200

[[redirects]]
    from = "/cv.html"
    to = "/html/cv.html"
    status = 200

[[redirects]]
    from = "/games.html"
    to = "/html/games.html"
    status = 200

[[redirects]]
    from = "/websites.html"
    to = "/html/websites.html"
    status = 200

[[redirects]]
    from = "/*"
    to = "/html/no-found.html"
    status = 404